spring:
  application:
    name: web-backend-template-spring

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pointops?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: pointi
    password: core0908

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 9000
  servlet:
    context-path: /
  error:
    include-message: always

app:
  front-origins: http://__FRONT_URL__